// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvqnkdxmbhwxkuknedby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2cW5rZHhtYmh3eGt1a25lZGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDQzNjEsImV4cCI6MjA2ODA4MDM2MX0.DB3qV4L4b03RJ0zTn1W0hKnAh8rPqblii2z1POtR65A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});